Repository Oskmey/-Agile-software-project-management, pull requests merged in 2024-04, with the labels that each got.

#79 Update kanban-board-template.md
  .github/ISSUE_TEMPLATE/kanban-board-template.md
Labels: documentation

#86 Player control fixes
  DAT257AgileProject/Assets/Prefabs/Player.prefab
  DAT257AgileProject/Assets/Prefabs/TutorialText.prefab
  DAT257AgileProject/Assets/Prefabs/UI/GameplayHUD.prefab
  DAT257AgileProject/Assets/Prefabs/Utility/TrashHandler.prefab
  DAT257AgileProject/Assets/Resources/Inputs/PlayerInputActions.inputactions
  DAT257AgileProject/Assets/Scenes/OtherSampleScene.unity
  DAT257AgileProject/Assets/Scenes/Player Control Fixes.unity
  DAT257AgileProject/Assets/Scenes/Player Control Fixes.unity.meta
  DAT257AgileProject/Assets/Scenes/SampleScene.unity
  DAT257AgileProject/Assets/Scenes/SampleScene.unity.meta
  DAT257AgileProject/Assets/Scripts/ArrowBoxMinigame.cs
  DAT257AgileProject/Assets/Scripts/FishingFeature.cs
  DAT257AgileProject/Assets/Scripts/GameManager.cs
  DAT257AgileProject/Assets/Scripts/Player/PlayerController.cs
  DAT257AgileProject/Assets/Scripts/Player/PlayerInputActions.cs
  DAT257AgileProject/Assets/Scripts/Player/PlayerInputActions.cs.meta
  DAT257AgileProject/Assets/Scripts/Recycling/RecyclingManager.cs
  DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
  DAT257AgileProject/ProjectSettings/EditorBuildSettings.asset
  DAT257AgileProject/ProjectSettings/QualitySettings.asset
  DAT257AgileProject/ProjectSettings/TagManager.asset
Labels: bug

#87 Fishing minigame fixes
  DAT257AgileProject/Assets/Prefabs/ArrowBoxMinigame.prefab
  DAT257AgileProject/Assets/Scenes/Player Control Fixes.unity
  DAT257AgileProject/Assets/Scripts/ArrowBoxMinigame.cs
  DAT257AgileProject/Assets/Scripts/FishingFeature.cs
  DAT257AgileProject/Assets/Scripts/GameplayHud/GameplayHudHandler.cs
  DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
  DAT257AgileProject/ProjectSettings/TagManager.asset
Labels: bug

#91 Menu
  DAT257AgileProject/Assets/Prefabs/UI/Menu.meta
  DAT257AgileProject/Assets/Prefabs/UI/Menu/MainMenuCanvas.prefab
  DAT257AgileProject/Assets/Prefabs/UI/Menu/MainMenuCanvas.prefab.meta
  DAT257AgileProject/Assets/Scenes/Main Menu.unity
  DAT257AgileProject/Assets/Scenes/Main Menu.unity.meta
  DAT257AgileProject/Assets/Scripts/Menus.meta
  DAT257AgileProject/Assets/Scripts/Menus/MainMenu.cs
  DAT257AgileProject/Assets/Scripts/Menus/MainMenu.cs.meta
  DAT257AgileProject/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Outline.mat
  DAT257AgileProject/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#93 Fixing tests and more from user story 17
  DAT257AgileProject/Assets/Scenes/Game/World.unity
  DAT257AgileProject/Assets/Scenes/Test/RecyclingTest.unity
  DAT257AgileProject/Assets/Scripts/GameLogic/Fishing/FishingLoop.cs
  DAT257AgileProject/Assets/Scripts/GameLogic/GameManager.cs
  DAT257AgileProject/Assets/Scripts/GameLogic/Minigames/ArrowBox/ArrowBoxMinigame.cs
  DAT257AgileProject/Assets/Scripts/GameLogic/Minigames/Minigame.cs
  DAT257AgileProject/Assets/Scripts/GameLogic/Minigames/MinigameManager.cs
  DAT257AgileProject/Assets/Scripts/Player/PlayerStatsManager.cs
  DAT257AgileProject/Assets/Scripts/Recycling/RecyclingMachine.cs
  DAT257AgileProject/Assets/Scripts/Recycling/RecyclingManager.cs
  DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
  DAT257AgileProject/Assets/Tests/EditMode/Recycling/RecyclingTests.cs
  DAT257AgileProject/Assets/Tests/EditMode/Trash/TrashDataTests.cs
  DAT257AgileProject/Assets/Tests/PlayMode/RecyclingTests.cs
  DAT257AgileProject/Assets/Tests/PlayMode/Trash/TrashHandlerTests.cs
  DAT257AgileProject/ProjectSettings/EditorBuildSettings.asset
Labels: bug

#103 User story 24 credit screen
  DAT257AgileProject/Assets/Prefabs/UI/Menu/MainMenuCanvas.prefab
  DAT257AgileProject/Assets/Scenes/Game/Main Menu.unity
  DAT257AgileProject/Assets/Scripts/Menus/OpenLink.cs
  DAT257AgileProject/Assets/Scripts/Menus/OpenLink.cs.meta
Labels: enhancement

#106 Credit screen... forgot to save some stuff
  DAT257AgileProject/Assets/Prefabs/UI/Menu/MainMenuCanvas.prefab
  DAT257AgileProject/Assets/Scenes/Game/Main Menu.unity
Labels: bug

#111 User story 13 different types of water
  DAT257AgileProject/Assets/Prefabs/Fishing Spot.prefab
  DAT257AgileProject/Assets/Scenes/Oskar's World.unity
  DAT257AgileProject/Assets/Scripts/Fishing/FishingSpot.cs
  DAT257AgileProject/Assets/Scripts/Fishing/FishingSpotRarities.cs
  DAT257AgileProject/Assets/Scripts/Fishing/FishingSpotRarities.cs.meta
  DAT257AgileProject/Assets/Scripts/Fishing/RarityPercentageData.cs
  DAT257AgileProject/Assets/Scripts/Fishing/RarityPercentageData.cs.meta
  DAT257AgileProject/Assets/Scripts/Player/PlayerController.cs
  DAT257AgileProject/Assets/Scripts/Trash/TrashHandler.cs
Labels: enhancement

#110 User story 23 facts screen
  DAT257AgileProject/Assets/Prefabs/UI/Menu/MainMenuCanvas.prefab
  DAT257AgileProject/Assets/Prefabs/UI/Menu/Subheader.prefab
  DAT257AgileProject/Assets/Prefabs/UI/Menu/Subheader.prefab.meta
  DAT257AgileProject/Assets/Prefabs/UI/Menu/Wiki Item.prefab
  DAT257AgileProject/Assets/Prefabs/UI/Menu/Wiki Item.prefab.meta
  DAT257AgileProject/Assets/Scripts/Menus/OpenLink.cs
  DAT257AgileProject/Assets/Scripts/Menus/SubheaderHandler.cs
  DAT257AgileProject/Assets/Scripts/Menus/SubheaderHandler.cs.meta
  DAT257AgileProject/Assets/Scripts/Menus/WikiContainer.cs
  DAT257AgileProject/Assets/Scripts/Menus/WikiContainer.cs.meta
  DAT257AgileProject/Assets/Scripts/Menus/WikiHandler.cs
  DAT257AgileProject/Assets/Scripts/Menus/WikiHandler.cs.meta
Labels: enhancement
